apiVersion: v1
entries:
  redis:
  - annotations:
      category: Database
    apiVersion: v1
    appVersion: 6.0.9
    created: "2020-12-07T13:32:40.250989946Z"
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: fb24e1b0ee9ead5f23e63f8e0dc0c7080853d40ec81ac39671d7bc4092e8aa41
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - https://raw.githubusercontent.com/guomli/demo/master/charts/redis-11.3.1.tgz
    version: 11.3.1
generated: "2020-12-08T02:31:13Z"
serverInfo: {}
